markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
sass:
  sass_dir: _sass
  style: compressed
siteurl: https://www.w3.org/Privacy/permissions-ws-2022/
baseurl: /Privacy/permissions-ws-2022
permalink: /:categories/:title/
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock